---

- hosts: web
  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start the Apache Service
    service: name=apache2 state=started 



- hosts: db
  tasks:
  - name: Install Databases Packages
    apt: name=mariadb-server state=present

  - name: Start the Database Service
    service: name=mysql state=started 
