---

- hosts: web

  vars: 
    http_doc: "/var/www/html/test1"

  vars_prompt:
  - name: name
    prompt: What is the username you want use ?
  
  tasks:
  - name: Install Apache Packages on Ubuntu
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Start the Apache Service on Ubuntu
    service: name=apache2 state=started 
    when: ansible_os_family == "Debian"
  
  - name: Install Apache Packages on Redhat
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start the Apache Service on Redhat
    service: name=httpd state=started 
    when: ansible_os_family == "RedHat"

  - name: Checking the Document Root
    command: ls {{http_doc}}
    register: result1
    ignore_errors: yes

  - debug: msg="Unable to fine Document Root"
    when: result1|failed

  - name: Create New Document Root as specified.
    file: path={{http_doc}} state=directory
    when: result1|failed

  - name: Deploy Apache Custom Configuration 
    template: src=templates/apache2.j2 dest=/etc/apache2/apache2.conf
    notify:
      - Restart Apache2

  - name: Force the Handlers
    meta: flush_handlers

  - name: Deploy Dynamic WebPage. 
    template: src=templates/info.j2 dest={{http_doc}}/info.html
    notify: 
      - Restart Apache2

  - name: Deploy Static WebPage. 
    copy: src=files/index.html dest={{http_doc}}/index.html

  - debug: msg="The Username you supplied at prompt is :{{name}}"

  handlers:
  - name: Restart Apache2
    service: name=apache2 state=restarted

- hosts: db
  tasks:
  - name: Install Databases Packages
    apt: name=mariadb-server state=present

  - name: Start the Database Service
    service: name=mysql state=started 
