---

- name: Deploy Index Template Site File
  template: src=templates/index.j2 dest={{doc_root}}/index.html

- name: Deploy Index Static Site File
  copy: src=templates/index.j2 dest={{doc_root}}/static.html

- name: Download Mario Image from Web.
  get_url: url=http://www.mariomayhem.com/downloads/wallpapers/7/nsmb_wp7_1280.jpg dest={{doc_root}}/mario.jpg mode=0755

- name: Deploy Info Dynamic Site File
  template: src=templates/info.j2 dest={{doc_root}}/info.html
  notify:
    - Restart Apache-2

