---
# tasks file for win-tasks
- name: Create an user
  win_user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
    groups:
      - "{{ windows_group }}"
- name: Adding to domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_user }}"
    domain_admin_password: "{{ domain_password }}"
    state: domain
